BakeryShop/Controllers/BreadController.cs
using BakeryShop.Models;
using BakeryShop.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace BakeryShop.Controllers
{
    public class BreadController : Controller
    {
        private readonly IBreadRepository _breadRepository;
        private readonly ICategoryRepository _categoryRepository;

        public BreadController(IBreadRepository breadRepository, ICategoryRepository categoryRepository)
        {
            _breadRepository = breadRepository;
            _categoryRepository = categoryRepository;
        }
        [HttpGet]
        public IActionResult Details(int id)
        {
            var bread = _breadRepository.GetById(id);

            if (bread == null)
            {
                return NotFound();
            }
            return View(bread);


        }
        [HttpGet]
        public ViewResult List(string category)
        {
            IEnumerable<Bread> breads;
            string currentCategory;

            if (string.IsNullOrEmpty(category))
            {
                breads = _breadRepository.GetAll().OrderBy(p => p.Name);
                currentCategory = "Produsele noastre";
            }
            else
            {
                breads = _breadRepository.GetAll().Where(b => b.Category.CategoryName == category).OrderBy(p => p.Name);
                currentCategory = _categoryRepository.GetAllCategories().FirstOrDefault(c => c.CategoryName == category)?.CategoryName;
            }


            return View(new BreadListViewModel
            {
                Breads = breads,
                CurrentCategory = currentCategory

            });

        }

    }
}

BakeryShop/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace BakeryShop.Controllers
{
    public class ContactController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
    }
}

BakeryShop/Views/Shared/_BreadCard.cshtml
@model Bread

<div class="row">
    <div class="col-sm-4">
        <div class="card" style="width: 21rem;height:605px;">
            <img src="@Model.ImageThumbnailUrl" asp-append-version="true" class="card-img-top img-fluid img-thumbnail" alt="" style="width:100%;height:300px;" />
            <!--class="card-img-top" src="~/Images/bread.jpg" alt="">-->
            <div class="card-body">
                <h3 class="pull-right">
                    @Model.Price.ToString("c")
                </h3>
                <h3>
                    <a asp-controller="Bread" asp-action="Details" asp-route-id="@Model.BreadId">@Model.Name</a>
                </h3>
                <p class="card-text">@Model.Description</p>
                <div class="addToCart">
                    <p class="button">
                        <a class="btn btn-primary"
                           asp-route-id="@Model.BreadId">Add to cart</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

BakeryShop/Views/Shared/_Carousel.cshtml
<div id="carouselExampleInterval" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active" data-interval="3000">
            <img src="~/Images/carousel3.jpg" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item" data-interval="2000">
            <img src="~/Images/carousel2.jpg" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="~/Images/carousel1.jpg" class="d-block w-100" alt="...">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleInterval" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleInterval" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

BakeryShop/Views/Shared/_ContactPartial.cshtml
<ul class="navbar-nav">
    <li class="nav-item">
        <a class="nav-link text-dark" asp-controller="Contact" asp-action="Index">Contact</a>
    </li>
</ul>

BakeryShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BakeryShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BakeryShop</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Bread" asp-action="List">Produsele noastre</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                    <partial name="_ContactPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - BakeryShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>